# Generated by Django 4.1 on 2023-10-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image_remove_article_image_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Author',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='main.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
