# Generated by Django 4.1 on 2023-10-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_author_article_author_remove_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='main.image'),
        ),
    ]
