# Generated by Django 4.1 on 2023-10-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article'),
        ),
    ]
